- name: Install newsboat
  become: yes
  package:
      name: newsboat
      state: present
- name: Ensure newsboat dirs exists
  file:
      path: "{{ item }}"
      state: directory
  loop:
      - "~/.newsboat"
      - "~/.pqrs/newsboat"
- name: Render configuration
  template:
      src: config.j2
      dest: ~/.pqrs/newsboat/config
- name: Link configuration
  file:
      src: ~/.pqrs/newsboat/config
      dest: ~/.newsboat/config
      state: link
      force: yes
- name: Ensure urls file exists
  file:
      path: ~/.pqrs/newsboat/urls
      state: touch
- name: Link url file
  file:
      src: ~/.pqrs/newsboat/urls
      dest: ~/.newsboat/urls
      state: link
      force: yes
