- name: Ensure golang stack installed
  become: yes
  package:
    name: golang
    state: present
  when: role_version is version("0.5.1", "lt")
- name: Clone rmapi
  git:
    repo: "git@github.com:juruen/rmapi.git"
    dest: "~/Installed/rmapi"
    accept_hostkey: yes
    update: no
  when: role_version is version("0.5.1", "lt")
- name: Install rmapi
  shell: go build
  args:
    chdir: "~/Installed/rmapi"
  when: role_version is version("0.5.1", "lt")
- name: Rename rmapi to rmapi-original
  command: mv ~/Installed/rmapi/rmapi ~/.pqrs/bin/rmapi-original
  args:
    removes: ~/Installed/rmapi/rmapi
  when: role_version is version("0.5.1", "lt")
- name: Install rmapi-wrapper
  template:
    src: rmapi.j2
    dest: ~/.pqrs/bin/rmapi
    mode: u+x
  when: role_version is version("0.1.0", "lt")
